### ISSUE TITLE
Many duplicate keys in raw/sources.bib

### ISSUE THREAD

**Issue by xrotwang** [tupian-language-resources/tuled#16]
There are a lot of duplicates in `raw/sources.bib` - basically all the entries taken from Glottolog, with numeric keys, for example.

**Comment by xrotwang** [comment]
@LanguageStructure `raw/sources.bib` has gained lots of duplicates again. Some items even show up three times, although that may not only be duplication but actual errors, e.g.:
```bibtex
@mastersthesis{borella2000aspectos,
  title={Aspectos morfossintáticos da língua Aweti (Tupi)},
  author={Borella, Cristina de Cássia and others},
  year={2000},
  school={Universidade de Campinas},
  note={Unpublished master's thesis}
}


@mastersthesis{borella2000aspectos,
  title={Aspectos morfossintáticos da língua Aweti (Tupi)},
  author={Ribeiro, Maria de J. Pacheco},
  year={2010},
  school={Universidade Federal de Rondônia},
  note={Unpublished master's thesis}
}
```

I think you'd need to curate the references using a tool that helps with such issues (and creates well-formed BibTeX).

**Comment by LanguageStructure** [comment]
I will take care of this in the next minutes

**Comment by xrotwang** [comment]
See also https://github.com/tupian-language-resources/tuled/pull/23

**Comment by LanguageStructure** [comment]
Have you fixed the file or should I do it?

**Comment by xrotwang** [comment]
The PR only fixes the BibTeX syntax - not the duplicates.

**Comment by LanguageStructure** [comment]
I will take care of the file!
