### ISSUE TITLE
Language sources

### ISSUE THREAD

**Issue by LanguageStructure** [tupian-language-resources/tuled#24]
I am trying to find the language file with the references (source) column. I can not find it. Help @StasReichert @xrotwang

**Comment by LinguList** [comment]
@StasReichert deleted the file 3 days ago: https://github.com/tupian-language-resources/tuled/commit/c38b7a65b46d1b065dc925fa6f3d86a09b3974e3

Not clear why, was it by accident?

**Comment by LanguageStructure** [comment]
dann füge ich die sources wieder hinzu.
