### ISSUE TITLE
Please revert to original concept list, the list is again corrupted!

### ISSUE THREAD

**Issue by LinguList** [tupian-language-resources/tuled#25]
I just wanted to add the concept list for the TULED paper to concepticon, but I cannot do so, if you constantly keep messing up the standards we use to display concepts. Please, really, do not replace `etc/concepts.tsv` completely with new files every time, especially not with old files, as this makes it impossible for us to keep track with the data. Instead, run `cldfbench lexibank.makecldf tuled` every time after doing something and do not upload data if the code fails.

**Comment by LanguageStructure** [comment]
@StasReichert bitte!
@LinguList was the deletion from my account?

**Comment by LinguList** [comment]
Deletion was done by Stas' account.
