### ISSUE TITLE
Concept List now Mapped

### ISSUE THREAD

**Issue by LinguList** [tupian-language-resources/tuled#26]
The concept list was now mapped as [Gerardi-2021-414](https://github.com/concepticon/concepticon-data/blob/master/concepticondata/conceptlists/Gerardi-2021-414.tsv) and should be included into our CLDF creation process.

Note that any changes to the concept list should from now on be discussed before they are applied (i.e., adding new concepts).

@LanguageStructure, can you confirm that the 414 concepts is what we will need for now? Note also that the paper states there are 404 concepts, while version 0.9 has 394 and version 0.10 has 414, so I selected 414 since this was where we had data mapped to concepticon...

**Comment by xrotwang** [comment]
AFAICT, the list hasn't been released with Concepticon yet. So maybe we should update it to reflect the 418 concepts which have forms (or the 423 concepts here https://github.com/tupian-language-resources/tuled/blob/master/etc/concepts.tsv ?)
