### ISSUE TITLE
Prenasalized sounds rendering

### ISSUE THREAD

**Issue by LinguList** [tupian-language-resources/tuled#31]
There is an inconsistent rendering of mb vs. superscript-n+m and the like. I will design a test for all the data in order to make sure we do not have instances like mb, ŋk, and the like but render them as pre-nasalized, for consistency.

**Comment by LanguageStructure** [comment]
good idea! Carolina and I were talking about this earlier on today

**Comment by LinguList** [comment]
The check will be as before, but what you two can do in edictor is to use the filter feature: open the app, paste `tokens=mb` into "filter by column", and you have all cases with mb, same for ŋk, ŋg, etc., and in edictor, you can use x-sampe, and just write `^nb` for superscript-n+b, right?

**Comment by LanguageStructure** [comment]
Sure! We will do this, staring in 20 min from now

**Comment by LanguageStructure** [comment]
I think we are done

**Comment by LinguList** [comment]
Okay, I will later make a check, when we go for finalizing 1.0. We leave 
this open until then.

**Comment by LanguageStructure** [comment]
great!
