### ISSUE TITLE
Integrate sources.bib via git submodule

### ISSUE THREAD

**Issue by xrotwang** [tupian-language-resources/tuled#32]
The bibliography is available as github repos now: https://github.com/tupian-language-resources/bibliography and should be pulled into `raw/bibliography` as git submodule.

**Comment by xrotwang** [comment]
The clean transparent look of https://github.com/tupian-language-resources/tudet/tree/main/raw turned me into a fan of git submodules.

**Comment by LanguageStructure** [comment]
I am glad this function exists at all. It allows us to easily release on
TuDeT without depending on UD
