### ISSUE TITLE
errors with entries

### ISSUE THREAD

**Issue by LinguList** [tupian-language-resources/tuled#34]
|   Type | ID                      | Value   | Form   | Graphemes   | Segments          |
|-------:|:------------------------|:--------|:-------|:------------|:------------------|
|      1 | Juma-84_comb-1          | kɨwabm  | kɨwabm |             | k ɨ + w + + a b m |
|      1 | Makurap-136_fleshmeat-1 | ɲirǝ̃ʔ_  | ɲirǝ̃ʔ_ |             | ɲ i r ǝ̃ ʔ +       |

A plus should not be at the end of a sequence, and no two `+ +` inside.

**Comment by LanguageStructure** [comment]
@StasReichert correct this on GitHub. I will do it on EDICTOR

**Comment by LinguList** [comment]
@StasReichert, please do not correct anything on github for now. I modified the code, and am still working on it, so I'd rather do this myself this time, okay?

**Comment by StasReichert** [comment]
Sure, I will do nothing so as not to interfere and cause any problems.
