### ISSUE TITLE
Error with entries

### ISSUE THREAD

**Issue by LinguList** [tupian-language-resources/tuled#38]
I just looked at the most recent version and found the following errors (I think @StasReichert, if possible, you should run this error analysis more often, so you can coordinate the problems):

```
WARNING Invalid Language ID Açuã Tupi
WARNING Entry ID=61, concept=CHIEF / MASTER / OWNER, language=Karo is empty                                                                       
WARNING Missing concept BLUE YELLOW MACAW
WARNING Missing concept SOUR / BITTER
WARNING Missing concept SURUBIM
WARNING Entry ID=1102, concept=TAPIR, language=Makurap is empty
WARNING Entry ID=1260, concept=FINGER, language=Wayoro is empty
WARNING Entry ID=1643, concept=HEN / CHICKEN, language=Tupari is empty
WARNING Missing concept RED MACAW
WARNING Entry ID=1711, concept=PACA, language=Tupari is empty
WARNING Entry ID=1720, concept=PECCARY (collared), language=Tupari is empty
WARNING Entry ID=1859, concept=WIND, language=Tupari is empty
WARNING Missing concept HARPY EAGLE
WARNING Entry ID=2255, concept=ANACONDA, language=Mekens is empty
WARNING Entry ID=2334, concept=DRAW / PAINT, language=Mekens is empty
WARNING Entry ID=2654, concept=PIRANHA, language=Cinta-Larga is empty
WARNING Entry ID=2676, concept=STAR, language=Cinta-Larga is empty
WARNING Entry ID=2715, concept=ANACONDA, language=Gavião is empty
WARNING Entry ID=2722, concept=ARMADILLO, language=Gavião is empty
WARNING Entry ID=3022, concept=SON OF WOMAN, language=Gavião is empty
WARNING Entry ID=3287, concept=PAN, language=Monde is empty
WARNING Entry ID=3536, concept=SAND, language=Arua is empty
WARNING Entry ID=3551, concept=SNAIL, language=Arua is empty
WARNING Entry ID=3648, concept=PACU FISH, language=Matanau is empty
WARNING Entry ID=3675, concept=WHITE, language=Matanau is empty
WARNING Missing concept LIGHTNING
WARNING Entry ID=3900, concept=ARMADILLO, language=Surui-Paiter is empty
WARNING Entry ID=3966, concept=DAUGHTER OF WOMAN, language=Surui-Paiter is empty
WARNING Entry ID=3967, concept=DAUGHTER OF MAN, language=Surui-Paiter is empty
WARNING Entry ID=4655, concept=TAPIR, language=Arikem is empty
WARNING Entry ID=5438, concept=GNAT / PIUM, language=Mundurukú is empty
WARNING Entry ID=5561, concept=MOON, language=Mundurukú is empty
WARNING Entry ID=6030, concept=WOODPECKER, language=Kuruaya is empty
WARNING Entry ID=6413, concept=ANACONDA, language=Awetí is empty
WARNING Entry ID=6836, concept=FOUR, language=Parakana is empty
WARNING Entry ID=8672, concept=GUAN / JACU, language=Apiaka is empty
WARNING Entry ID=9288, concept=GUAN / JACU, language=Amondawa is empty
WARNING Entry ID=10357, concept=DRY, language=Kayabi is empty
WARNING Missing concept ACARÉ / CAIMAN / CROCODILE
WARNING Entry ID=11082, concept=SNAKE, language=Guajá is empty
WARNING Entry ID=11298, concept=BURY, language=Teko is empty
WARNING Entry ID=11616, concept=AFTER, language=Wayampi is empty
WARNING Entry ID=12837, concept=SNAKE, language=Turiwara is empty
WARNING Entry ID=14148, concept=GRASS, language=Nheengatu is empty
WARNING Entry ID=14149, concept=GREEN, language=Nheengatu is empty
WARNING Entry ID=14273, concept=SNAKE, language=Nheengatu is empty
WARNING Entry ID=14566, concept=SNAKE, language=Tupí Austral is empty
WARNING Entry ID=15304, concept=GIRL, language=Siriono is empty
WARNING Entry ID=16253, concept=FOOD, language=Mbya is empty
WARNING Entry ID=17385, concept=WANT, language=Ache is empty
WARNING Entry ID=17847, concept=AFTER, language=Tapiete is empty
WARNING Entry ID=17890, concept=BROTHER, older of man, language=Tapiete is empty
WARNING Entry ID=18281, concept=SUN, language=Ñandeva is empty
WARNING Entry ID=18315, concept=BROTHER, younger of woman, language=Apapokuva is empty
WARNING Entry ID=19316, concept=BROTHER, older of woman, language=Apapokuva is empty
WARNING Missing concept STAY
WARNING Missing concept FLOAT
WARNING Missing concept ENEMY
WARNING Missing concept BE HUNGRY
WARNING Missing concept SHRIMP
WARNING Missing concept BABY CARRIER
WARNING Missing concept EARRING
WARNING Missing concept SCREAM
WARNING Missing concept LIP
WARNING Missing concept COOK
WARNING Entry ID=22369, concept=THROW, language=Tupari is empty
WARNING Entry ID=22371, concept=MOTHER-IN-LAW (of woman), language=Tupari is empty
WARNING Missing concept PLANT(v)
WARNING Entry ID=22479, concept=FOUR, language=Surui-Paiter is empty
WARNING Missing concept RATTLE
WARNING Missing concept VAGINA
WARNING Entry ID=22601, concept=KNIFE, language=Xipaya is empty
WARNING Entry ID=22602, concept=KNIFE, language=Juruna is empty
WARNING Entry ID=22721, concept=AFTER, language=Warazu is empty
WARNING Entry ID=22722, concept=TOMORROW, language=Warazu is empty
WARNING Missing concept FOREST
WARNING Entry ID=22796, concept=DIGGING STICK, language=Makurap is empty
WARNING Missing concept GRILL
WARNING Entry ID=22818, concept=HUNT, language=Surui-Paiter is empty
WARNING Entry ID=22819, concept=HUNT, language=Surui-Paiter is empty
WARNING Entry ID=22829, concept=SWEEP, language=Surui-Paiter is empty
WARNING Missing concept SMELL
WARNING Missing concept STENCH
WARNING Entry ID=22930, concept=BEADS, language=Siriono is empty
WARNING Missing concept SOUND
WARNING Missing concept ANUS
WARNING Missing concept CLOTHES
WARNING Missing concept FAN
WARNING Entry ID=23133, concept=BOY, language=Mekens is empty
WARNING Missing concept SIEVE
WARNING Entry ID=23183, concept=SPROUT, language=Makurap is empty
WARNING Entry ID=23201, concept=I, language=Awetí is empty
WARNING Missing concept SIEVE / STRAIN
WARNING Missing concept MATERNAL GRANDMOTHER
WARNING Entry ID=23381, concept=(Brazilian) CEDAR, language=Asuriní Tocantins is empty
WARNING Entry ID=23389, concept=SALT, language=Jora is empty
WARNING Entry ID=23390, concept=GRASS, language=Karo is empty
WARNING Entry ID=23417, concept=DRY (state), language=Mekens is empty
WARNING Missing concept MIRROR
WARNING Missing concept SHINE
WARNING Missing language Açuã Tupi
```

**Comment by LanguageStructure** [comment]
@StasReichert maybe you can push the file with the new concepts and languages, and bib to Github. I will take care of the empty slots

**Comment by StasReichert** [comment]
Although I did push the two tsv files on Github it turned out the code does it automatically (fetching the Google Sheets and using them instead of tsv files), so there was no need for my action there. 
However, when trying to run cldfbench I am asked for the path to the Google API key file. What exactly should I enter there? It doesn't seem to be the path to the Google Sheets and I am a bit at a loss there ...

**Comment by LinguList** [comment]
You need to get an API key from google for the sheet: 
https://support.google.com/googleapi/answer/6158862?hl=en

**Comment by LinguList** [comment]
The use of the API is one of the new changes we introduced last time. It 
allows us to skip the often deleterious process of just uploading files 
via the github interface and also enhances collaboration, as we thought.

**Comment by StasReichert** [comment]
@LinguList, thank you for the link and the explanation. I think the idea of collaboration with APIs is great, it really is an effective way of dealing with the changes in the data as we have a single file to work on (plus, your code eliminates most of the work we'd have to perform on github). This is the first time I am working with Google APIs, so I am afraid I may still bother you with a question or two. I created a Google Sheet API key for a dummy project, but is that what I need to work on our spreadsheet?

**Comment by LinguList** [comment]
Yes, you need this, you have a json file and just pass this as the key.

**Comment by StasReichert** [comment]
Everything seems to work great and we eliminated almost all of the errors. What remains are a few errors of the type:
* CONCEPT FOREST
which we cannot understand as the concepts are all in the Google concepts sheet and are downloaded by the cldfbench when I run it.
There is also one single error of the type LANGUAGE that we cannot get rid of:
* LANGUAGE Açuã Tupi
We added a language a few weeks ago together with another one, but only Açuã remains unrecognized.

**Comment by LinguList** [comment]
The concepts error is probably because we switch to full Concepticon 
integration in the code now, mentioning the concept list in concepticon. 
We can revert this, but I prefer to have rigorous checks here and not 
much fluctuation.

**Comment by LinguList** [comment]
The language has diacritics, and our language identiifers are not 
allowed to have diacritics. It is important to pay attention to this, as 
you can give a language a name in any Unicode character sequence, but 
the ID should not have an accent, and likewise, I prefer the DOCULECT in 
edictor to serve as the ID. But I'll have to check this a bit later.

**Comment by LinguList** [comment]
In confirmed this: the ID column in the google sheet was faulty. It should be only alphabetic with numbers, but no diacritics, like normall variables in Python. I have adjusted this. The language mapping from edictor to cldf should then use the langauge name (need to make sure this works when updating).

**Comment by LinguList** [comment]
@StasReichert, I'll check the code on Monday, as I don't have time today. By then, I can tell you what issues remain. You could otherwise also run and see if the language ID problem has been solved with my modification of the language ID in the google sheet.

**Comment by StasReichert** [comment]
@LinguList, your modification worked like a charm and the language ID problem no longer appears in the errors.md when I run cldfbench. Thank you for taking the time to help us there! 
We won't be able to continue our work until Tuesday morning, either, but I hope the remaining issue(s) will be resolved quickly then.
