### ISSUE TITLE
Small new release needed

### ISSUE THREAD

**Issue by LinguList** [tupian-language-resources/tuled#39]
We have now integrated the Concept list from concepticon in the code and also upgraded to lexibank's most recent version. In order to keep datasets in sync with Glottolog etc., we will need to release the data, to guarantee compatibility with other software packages (also lingpy etc.). 

I suggest we do this ASAP, but if you want to update the languages list etc., it would probably be good to do this before, and then let us know.

**Comment by LanguageStructure** [comment]
I/we will do this today/tomorrow

**Comment by LinguList** [comment]
Nice. The code base is also working now again.
